export const actionTypes = {
    APPEND_HISTORY: 'APPEND_HISTORY',
    SET_TURN_ORDER: 'SET_TURN_ORDER',
    END_GAME: 'END_GAME',
    END_TURN: 'END_TURN',
    CHANGE_PHASE: 'CHANGE_PHASE',
    SET_TEAMS: 'SET_TEAMS',
    CHANGE_ZONE: 'CHANGE_ZONE',
    ADD_TO_ZONE: 'ADD_TO_ZONE',
    REMOVE_FROM_ZONE: 'REMOVE_FROM_ZONE',
    SHUFFLE_ZONE: 'SHUFFLE_ZONE',
    CHANGE_CARD: 'CHANGE_CARD',
};
